module.exports = require('coa').Cmd()
  .name(process.argv[1])
    .title('Yadisk.')
    .helpful()
    .opt()
        .name('version') .title('Version')
        .short('v').long('version')
        .flag()
        .only()
        .act(function() { return JSON.parse(FS.readFileSync(PATH.resolve(__dirname, '..', 'package.json'))).version })
        .end()
    // TODO add titles to commands
    .cmd().name('mkdir').apply(require('./commands/mkdir')).end()
    .cmd().name('publish').apply(require('./commands/publish')).end()
    .cmd().name('unpublish').apply(require('./commands/unpublish')).end()
    .cmd().name('rm').apply(require('./commands/rm')).end()
    .cmd().name('cp').apply(require('./commands/cp')).end()
    .cmd().name('login').apply(require('./commands/login')).end()
    .cmd().name('logout').apply(require('./commands/logout')).end()
    .cmd().name('mv').apply(require('./commands/mv')).end();
